### PR TITLE
add `type` property to progress Buffer

### PR DESCRIPTION
**Pull request by zaggino**
PR for #3

### CODE REVIEW

**Comment by satazor** [comment]
@sheerun is this ok for you?

**Comment by sheerun** [comment]
That's fine with me :)

**Comment by satazor** [comment]
I've released `1.1.0` with this change. @sheerun could you please update bower's package.json?

**Comment by sheerun** [comment]
Bower doesn't seem to used. Neither any of its dependencies.

**Comment by satazor** [comment]
Hmmm ok

**Pull request merged**
